# Generated by Django 4.2.7 on 2025-09-14 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_valid_format', models.BooleanField()),
                ('is_deliverable', models.BooleanField()),
                ('smtp_status', models.CharField(max_length=50)),
                ('domain_info', models.TextField(default='{}')),
                ('spf_record', models.TextField(blank=True, null=True)),
                ('dkim_valid', models.BooleanField(null=True)),
                ('dmarc_record', models.TextField(blank=True, null=True)),
                ('validation_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_validation_results',
                'indexes': [models.Index(fields=['email'], name='email_valid_email_3fdb9b_idx'), models.Index(fields=['created_at'], name='email_valid_created_1c1361_idx')],
            },
        ),
    ]
